### ISSUE TITLE
You can use (boot.App/getBootDir) to find user's .boot

### ISSUE THREAD

**Issue by micha** [danielsz/boot-binstub#1]
Here: https://github.com/danielsz/boot-binstub/blob/master/src/danielsz/binstubs.clj#L10-L11

You can use instead

```
(boot.App/getBootDir)
```

That will give you the correct directory in case the user has `BOOT_HOME` set, for example.

**Comment by danielsz** [comment]
:+1:

**Comment by danielsz** [comment]
Fixed in 6f52c0a47632f98da11467a57a7dbeac5c07b134
